<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-10-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(default='unknow', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
=======
# Generated by Django 5.2.4 on 2025-10-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(default='unknow', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
>>>>>>> 89753d7a3ee7e84d925c5a0aad0c3b4ce46fad57
