# Generated by Django 5.2.4 on 2025-10-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesstapp', '0003_remove_fooditem_category_remove_fooditem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='food_items/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
