# Generated by Django 5.2.4 on 2025-10-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesstapp', '0004_fooditem_image_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restro-images/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
