# Generated by Django 5.2.4 on 2025-10-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesstapp', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='food_items',
        ),
    ]
